import { createElement } from '@lwc/engine-dom';
import FetchDataUsingWire from 'c/fetchDataUsingWire';

describe('c-fetch-data-using-wire', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-fetch-data-using-wire', {
            is: FetchDataUsingWire
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});